name: Sync Backend to Hugging Face

on:
  push:
    branches: [main]
    paths:
      - 'sidiktaut_web/backend/**'

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Konfigurasi Git (Pura-pura jadi Robot)
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

          # 2. Clone Space Hugging Face (Target)
          # Menggunakan token kamu untuk login otomatis
          git clone https://yudhadevsec:$HF_TOKEN@huggingface.co/spaces/yudhadevsec/Sidiktaut hf_space

          # 3. Pindah File
          # Masuk ke folder hasil clone tadi
          cd hf_space
          
          # Copy SEMUA isi folder backend dari GitHub ke sini
          # (Perintah cp -a akan mengcopy file hidden juga jika ada)
          cp -a ../sidiktaut_web/backend/. .
          
          # 4. Eksekusi Push
          echo "Persiapan push ke Hugging Face..."
          git add .
          git commit -m "Sync from GitHub: $GITHUB_SHA" || echo "Tidak ada perubahan baru."
          git push origin main