name: Sync Backend to Hugging Face

on:
  push:
    branches: [main]
    paths:
      - 'sidiktaut_web/backend/**'

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          # --- PERHATIKAN BAGIAN INI (BEDA DARI SEBELUMNYA) ---
          
          # 1. Wajib isi nama Repo GitHub kamu (Lihat dari screenshot kamu)
          github_repo_id: 'yudhadevsec/Sidiktaut-Project'
          
          # 2. Nama Repo Hugging Face Tujuan
          huggingface_repo_id: 'yudhadevsec/Sidiktaut'
          
          # 3. Jenis Repo (Space)
          repo_type: 'space'
          
          # 4. Token (Namanya jadi hf_token)
          hf_token: ${{ secrets.HF_TOKEN }}
          
          # 5. Folder yang mau dikirim (Namanya jadi subdirectory)
          subdirectory: 'sidiktaut_web/backend'